<?php

/*
 * This file is part of the ICanBoogie package.
 *
 * (c) Olivier Laviale <olivier.laviale@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\ICanBoogie\ActiveRecord;

use ICanBoogie\ActiveRecord;
use ICanBoogie\ActiveRecord\RecordNotFound;
use PHPUnit\Framework\TestCase;
use Test\ICanBoogie\Acme\Node;

final class RecordNotFoundTest extends TestCase
{
    /**
     * @var array<int, ActiveRecord|false>
     */
    private array $records;
    private RecordNotFound $exception;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->records = [

            1 => new Node(),
            2 => false,
            3 => new Node()

        ];

        $this->exception = new RecordNotFound("My message", $this->records);
    }

    public function test_message(): void
    {
        $this->assertEquals("My message", $this->exception->getMessage());
    }

    public function test_get_records(): void
    {
        $this->assertIsArray($this->exception->records);
        $this->assertSame($this->records, $this->exception->records);
    }
}
