sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - build

language: php

php:
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  - if [[ $TRAVIS_PHP_VERSION == "7.2" ]]; then make test-coveralls; else make test; fi
