name: test

on:
- push
- pull_request

jobs:
  phpunit:
    name: phpunit
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        php-version:
        - "8.4"
        - "8.5"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: xdebug
        php-version: "${{ matrix.php-version }}"
        ini-values: memory_limit=-1
        tools: composer:v2
        extensions: pdo_mysql, pdo_pgsql
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.composer/cache
          vendor
        key: "php-${{ matrix.php-version }}"
        restore-keys: "php-${{ matrix.php-version }}"

    - name: Install dependencies
      run: composer install --no-interaction --no-progress

    - name: Run PHPUnit
      run: make test-coveralls

    - name: Upload code coverage
      if: ${{ matrix.php-version == '8.4' }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        composer global require php-coveralls/php-coveralls
        php-coveralls --coverage_clover=build/logs/clover.xml -v
